import {Inter} from "next/font/google";
import "./globals.scss";
import Header from "@/components/header";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "WP Headless website",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header/>
        <main className="w-full sm:max-w-xs md:max-w-sm lg:max-w-md xl:max-w-lg mx-auto">
            {children}
        </main>
        </body>
        </html>
    );
}
